config/routes.rb
Rails.application.routes.draw do

  devise_for :users 
  resources :users, only: [:show]

  resources :champions, only: [:index, :show, :edit, :update, :create, :new]

  root to: 'champions#index'

end

app/models/ability.rb
#  create_table "abilities", force: true do |t|
#    t.string   "scales_from"
#    t.string   "key"
#    t.string   "name"
#    t.text     "description"
#    t.integer  "abilitable_id"
#    t.string   "abilitable_type"
#    t.datetime "created_at"
#    t.datetime "updated_at"
#  end


class Ability < ActiveRecord::Base
  belongs_to :abilitable, polymorphic: true
end

app/models/champion.rb
#  create_table "champions", force: true do |t|
#    t.string   "name"
#    t.text     "lore"
#    t.datetime "created_at"
#    t.datetime "updated_at"
#    t.string   "loadingart_file_name"
#    t.string   "loadingart_content_type"
#    t.integer  "loadingart_file_size"
#    t.datetime "loadingart_updated_at"
#    t.string   "primary_damage_type"
#    t.string   "thumbnail_file_name"
#    t.string   "thumbnail_content_type"
#    t.integer  "thumbnail_file_size"
#    t.datetime "thumbnail_updated_at"
#  end

class Champion < ActiveRecord::Base
  has_many :abilities, as: :abilitable

  has_attached_file :loadingart, :styles => { :medium => "308x560>", :small => "154x280" } 
  validates_attachment_content_type :loadingart, :content_type => /\Aimage\/.*\Z/

  has_attached_file :thumbnail, :styles => { :medium => "120x120>", :small => "60x60" } 
  validates_attachment_content_type :thumbnail, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  layout 'application'
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource_or_scope)
    # request.referrer
    redirect_to root_url
  end

end

app/controllers/champions_controller.rb
class ChampionsController < ApplicationController

  def new
    @champion = Champion.new
  end

  def create
    @champion = Champion.new(champ_params)
    if @champion.save
      redirect_to root_url
    else
      flash[:errors] = @champion.errors.full_messages
      render :new
    end
  end

  def index
    @champions = Champion.all
  end

  def show
    @champion = Champion.find_by_id(params[:id])

    render 'champions/_champion_show', locals: {champion: @champion}, layout: false
  end

  def edit
    @champion = Champion.find(params[:id])
  end

  def update
    @champion = Champion.find(params[:id])

    if @champion.update_attributes(champ_params)
      redirect_to root_url
    else
      flash.now[:errors] = @champion.errors.full_messages
      render :edit
    end
  end

  private

    def champ_params
      params.require(:champion).permit(:name, :lore, :loadingart, :thumbnail, :primary_damage_type)
    end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/champions_helper.rb
module ChampionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/champions/_champ_list.haml
.col-md-4
  .index-header.t-white
    %h2
      pick a champion:
  %hr.fading-horizontal-black.lil-margin-bot
  .index-body.fading-vertical
    - @champions.each do |c|
      .champ-info.t-white.lil-padding{ id: "champ#{ c.id }" }
        = image_tag c.thumbnail(:small), class: 'black-border'
        = c.name
        = c.primary_damage_type
        %hr.fading-horizontal-blue
  %hr.fading-horizontal-black.med-margin-top

app/views/champions/_champion_show.haml
#show_content.col-md-8
  - if @champion
    =@champion.name
    %ul
      %li.ability.passive
        = @champion.abilities.find_by(key: 'Passive').name
      %li.ability
        = @champion.abilities.find_by(key: 'Q').name
      %li.ability
        = @champion.abilities.find_by(key: 'W').name
      %li.ability
        = @champion.abilities.find_by(key: 'E').name
      %li.ability
        = @champion.abilities.find_by(key: 'R').name

app/views/champions/_form.haml
this is the form partial
%br

.champ-form.centered
  = semantic_form_for @champion, url: url do |f|
    = f.inputs do
      = f.semantic_errors
      = f.input :name
      = f.input :lore
      = f.input :primary_damage_type
      = f.input :thumbnail
    = f.actions do
      = f.action :submit, id: 'champ_submit'

app/views/champions/edit.haml
edit page
%br
= render partial: 'form', locals: { url: champion_path(@champion) }
%br

app/views/champions/index.haml
.champ-content.container.bg-dark-grey
  #champ_list
    = render 'champ_list'
  #champ_show
    = render 'champion_show'

:javascript

  $('.champ-info').click(function(e) {
    champ_id = e.currentTarget.id;
    var el = e.currentTarget;
    var champ_id = $(this).attr('id').split('champ')[1]
    $.ajax( {
      type: 'GET',
      url : '/champions/' + champ_id,
      action : 'show',
      dataType : 'text',
      success : function(responseData) {
        $('#champ_show').html(responseData);
      },
      error : function(xhr, status, errorThrown) {
        var response = $.parseJSON(xhr.responseText);
        console.log("failure")
      }
    } )
  } );

  $('.index-header').click(function() {
    $('#champ_show').html('');
  } );

app/views/champions/new.haml
new page
%br
= render partial: 'form', locals: { url: champions_path }
%br

app/views/layouts/application.haml
!!! 5
%html
  %head
    %title Adoraplol
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true 
    = csrf_meta_tags

  %body

  - if notice
    .notice
      =raw notice
  - if alert
    .alert
      =raw alert

  = render 'shared/header'

  = yield

  = render 'shared/footer'
  

app/views/shared/_footer.haml
.footer
  footer stuff

app/views/shared/_header.haml
.header
  header material

app/views/users/show.haml
THIS IS THE SHOW USER PAGE!!
- if @user
  = @user.email